package aoc.Harlequin.OBJs;

// Generated 25 May 2018 1:01:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * ApplicantMacInterview generated by hbm2java
 */
public class ApplicantMacInterview implements java.io.Serializable {

	private ApplicantMacInterviewId id;

	public ApplicantMacInterview() {
	}

	public ApplicantMacInterview(ApplicantMacInterviewId id) {
		this.id = id;
	}

	public ApplicantMacInterviewId getId() {
		return this.id;
	}

	public void setId(ApplicantMacInterviewId id) {
		this.id = id;
	}

}
