package aoc.Harlequin.OBJs;

// Generated 25 May 2018 1:01:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * ApplicantMacInterviewId generated by hbm2java
 */
public class ApplicantMacInterviewId implements java.io.Serializable {

	private int idMacApplicants;
	private String name;
	private String surname;
	private String jobName;
	private String rsaCitizen;
	private String idNumber;
	private String idVerified;
	private String sapCheck;
	private String criminalRecord;
	private String criminalRecordComments;
	private String workHistoryVerified;
	private String unionMember;
	private String unionName;
	private String applicantPassedInterview;
	private String applicantPresentable;
	private String applicantAtttitude;
	private String interviewComments;
	private String formalInterviewComplete;
	private Integer age;
	private String dateOfBirth;
	private String expiryDateOfPassport;
	private String workPermitValidity;
	private String cellNumber;
	private String EMail;
	private String jobType;
	private String driversLicenseVerified;
	private String dateFirstIssueLicense;
	private String licenseCode;
	private String expiryDateOfLicense;
	private String pdpExpiryDate;
	private String gender;
	private String city;
	private String country;
	private String homeLanguage;
	private String lastSmsDate;

	public ApplicantMacInterviewId() {
	}

	public ApplicantMacInterviewId(int idMacApplicants) {
		this.idMacApplicants = idMacApplicants;
	}

	public ApplicantMacInterviewId(int idMacApplicants, String name,
			String surname, String jobName, String rsaCitizen, String idNumber,
			String idVerified, String sapCheck, String criminalRecord,
			String criminalRecordComments, String workHistoryVerified,
			String unionMember, String unionName,
			String applicantPassedInterview, String applicantPresentable,
			String applicantAtttitude, String interviewComments,
			String formalInterviewComplete, Integer age, String dateOfBirth,
			String expiryDateOfPassport, String workPermitValidity,
			String cellNumber, String EMail, String jobType,
			String driversLicenseVerified, String dateFirstIssueLicense,
			String licenseCode, String expiryDateOfLicense,
			String pdpExpiryDate, String gender, String city, String country,
			String homeLanguage, String lastSmsDate) {
		this.idMacApplicants = idMacApplicants;
		this.name = name;
		this.surname = surname;
		this.jobName = jobName;
		this.rsaCitizen = rsaCitizen;
		this.idNumber = idNumber;
		this.idVerified = idVerified;
		this.sapCheck = sapCheck;
		this.criminalRecord = criminalRecord;
		this.criminalRecordComments = criminalRecordComments;
		this.workHistoryVerified = workHistoryVerified;
		this.unionMember = unionMember;
		this.unionName = unionName;
		this.applicantPassedInterview = applicantPassedInterview;
		this.applicantPresentable = applicantPresentable;
		this.applicantAtttitude = applicantAtttitude;
		this.interviewComments = interviewComments;
		this.formalInterviewComplete = formalInterviewComplete;
		this.age = age;
		this.dateOfBirth = dateOfBirth;
		this.expiryDateOfPassport = expiryDateOfPassport;
		this.workPermitValidity = workPermitValidity;
		this.cellNumber = cellNumber;
		this.EMail = EMail;
		this.jobType = jobType;
		this.driversLicenseVerified = driversLicenseVerified;
		this.dateFirstIssueLicense = dateFirstIssueLicense;
		this.licenseCode = licenseCode;
		this.expiryDateOfLicense = expiryDateOfLicense;
		this.pdpExpiryDate = pdpExpiryDate;
		this.gender = gender;
		this.city = city;
		this.country = country;
		this.homeLanguage = homeLanguage;
		this.lastSmsDate = lastSmsDate;
	}

	public int getIdMacApplicants() {
		return this.idMacApplicants;
	}

	public void setIdMacApplicants(int idMacApplicants) {
		this.idMacApplicants = idMacApplicants;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getRsaCitizen() {
		return this.rsaCitizen;
	}

	public void setRsaCitizen(String rsaCitizen) {
		this.rsaCitizen = rsaCitizen;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getIdVerified() {
		return this.idVerified;
	}

	public void setIdVerified(String idVerified) {
		this.idVerified = idVerified;
	}

	public String getSapCheck() {
		return this.sapCheck;
	}

	public void setSapCheck(String sapCheck) {
		this.sapCheck = sapCheck;
	}

	public String getCriminalRecord() {
		return this.criminalRecord;
	}

	public void setCriminalRecord(String criminalRecord) {
		this.criminalRecord = criminalRecord;
	}

	public String getCriminalRecordComments() {
		return this.criminalRecordComments;
	}

	public void setCriminalRecordComments(String criminalRecordComments) {
		this.criminalRecordComments = criminalRecordComments;
	}

	public String getWorkHistoryVerified() {
		return this.workHistoryVerified;
	}

	public void setWorkHistoryVerified(String workHistoryVerified) {
		this.workHistoryVerified = workHistoryVerified;
	}

	public String getUnionMember() {
		return this.unionMember;
	}

	public void setUnionMember(String unionMember) {
		this.unionMember = unionMember;
	}

	public String getUnionName() {
		return this.unionName;
	}

	public void setUnionName(String unionName) {
		this.unionName = unionName;
	}

	public String getApplicantPassedInterview() {
		return this.applicantPassedInterview;
	}

	public void setApplicantPassedInterview(String applicantPassedInterview) {
		this.applicantPassedInterview = applicantPassedInterview;
	}

	public String getApplicantPresentable() {
		return this.applicantPresentable;
	}

	public void setApplicantPresentable(String applicantPresentable) {
		this.applicantPresentable = applicantPresentable;
	}

	public String getApplicantAtttitude() {
		return this.applicantAtttitude;
	}

	public void setApplicantAtttitude(String applicantAtttitude) {
		this.applicantAtttitude = applicantAtttitude;
	}

	public String getInterviewComments() {
		return this.interviewComments;
	}

	public void setInterviewComments(String interviewComments) {
		this.interviewComments = interviewComments;
	}

	public String getFormalInterviewComplete() {
		return this.formalInterviewComplete;
	}

	public void setFormalInterviewComplete(String formalInterviewComplete) {
		this.formalInterviewComplete = formalInterviewComplete;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getExpiryDateOfPassport() {
		return this.expiryDateOfPassport;
	}

	public void setExpiryDateOfPassport(String expiryDateOfPassport) {
		this.expiryDateOfPassport = expiryDateOfPassport;
	}

	public String getWorkPermitValidity() {
		return this.workPermitValidity;
	}

	public void setWorkPermitValidity(String workPermitValidity) {
		this.workPermitValidity = workPermitValidity;
	}

	public String getCellNumber() {
		return this.cellNumber;
	}

	public void setCellNumber(String cellNumber) {
		this.cellNumber = cellNumber;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	public String getDriversLicenseVerified() {
		return this.driversLicenseVerified;
	}

	public void setDriversLicenseVerified(String driversLicenseVerified) {
		this.driversLicenseVerified = driversLicenseVerified;
	}

	public String getDateFirstIssueLicense() {
		return this.dateFirstIssueLicense;
	}

	public void setDateFirstIssueLicense(String dateFirstIssueLicense) {
		this.dateFirstIssueLicense = dateFirstIssueLicense;
	}

	public String getLicenseCode() {
		return this.licenseCode;
	}

	public void setLicenseCode(String licenseCode) {
		this.licenseCode = licenseCode;
	}

	public String getExpiryDateOfLicense() {
		return this.expiryDateOfLicense;
	}

	public void setExpiryDateOfLicense(String expiryDateOfLicense) {
		this.expiryDateOfLicense = expiryDateOfLicense;
	}

	public String getPdpExpiryDate() {
		return this.pdpExpiryDate;
	}

	public void setPdpExpiryDate(String pdpExpiryDate) {
		this.pdpExpiryDate = pdpExpiryDate;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getHomeLanguage() {
		return this.homeLanguage;
	}

	public void setHomeLanguage(String homeLanguage) {
		this.homeLanguage = homeLanguage;
	}

	public String getLastSmsDate() {
		return this.lastSmsDate;
	}

	public void setLastSmsDate(String lastSmsDate) {
		this.lastSmsDate = lastSmsDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApplicantMacInterviewId))
			return false;
		ApplicantMacInterviewId castOther = (ApplicantMacInterviewId) other;

		return (this.getIdMacApplicants() == castOther.getIdMacApplicants())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getSurname() == castOther.getSurname()) || (this
						.getSurname() != null && castOther.getSurname() != null && this
						.getSurname().equals(castOther.getSurname())))
				&& ((this.getJobName() == castOther.getJobName()) || (this
						.getJobName() != null && castOther.getJobName() != null && this
						.getJobName().equals(castOther.getJobName())))
				&& ((this.getRsaCitizen() == castOther.getRsaCitizen()) || (this
						.getRsaCitizen() != null
						&& castOther.getRsaCitizen() != null && this
						.getRsaCitizen().equals(castOther.getRsaCitizen())))
				&& ((this.getIdNumber() == castOther.getIdNumber()) || (this
						.getIdNumber() != null
						&& castOther.getIdNumber() != null && this
						.getIdNumber().equals(castOther.getIdNumber())))
				&& ((this.getIdVerified() == castOther.getIdVerified()) || (this
						.getIdVerified() != null
						&& castOther.getIdVerified() != null && this
						.getIdVerified().equals(castOther.getIdVerified())))
				&& ((this.getSapCheck() == castOther.getSapCheck()) || (this
						.getSapCheck() != null
						&& castOther.getSapCheck() != null && this
						.getSapCheck().equals(castOther.getSapCheck())))
				&& ((this.getCriminalRecord() == castOther.getCriminalRecord()) || (this
						.getCriminalRecord() != null
						&& castOther.getCriminalRecord() != null && this
						.getCriminalRecord().equals(
								castOther.getCriminalRecord())))
				&& ((this.getCriminalRecordComments() == castOther
						.getCriminalRecordComments()) || (this
						.getCriminalRecordComments() != null
						&& castOther.getCriminalRecordComments() != null && this
						.getCriminalRecordComments().equals(
								castOther.getCriminalRecordComments())))
				&& ((this.getWorkHistoryVerified() == castOther
						.getWorkHistoryVerified()) || (this
						.getWorkHistoryVerified() != null
						&& castOther.getWorkHistoryVerified() != null && this
						.getWorkHistoryVerified().equals(
								castOther.getWorkHistoryVerified())))
				&& ((this.getUnionMember() == castOther.getUnionMember()) || (this
						.getUnionMember() != null
						&& castOther.getUnionMember() != null && this
						.getUnionMember().equals(castOther.getUnionMember())))
				&& ((this.getUnionName() == castOther.getUnionName()) || (this
						.getUnionName() != null
						&& castOther.getUnionName() != null && this
						.getUnionName().equals(castOther.getUnionName())))
				&& ((this.getApplicantPassedInterview() == castOther
						.getApplicantPassedInterview()) || (this
						.getApplicantPassedInterview() != null
						&& castOther.getApplicantPassedInterview() != null && this
						.getApplicantPassedInterview().equals(
								castOther.getApplicantPassedInterview())))
				&& ((this.getApplicantPresentable() == castOther
						.getApplicantPresentable()) || (this
						.getApplicantPresentable() != null
						&& castOther.getApplicantPresentable() != null && this
						.getApplicantPresentable().equals(
								castOther.getApplicantPresentable())))
				&& ((this.getApplicantAtttitude() == castOther
						.getApplicantAtttitude()) || (this
						.getApplicantAtttitude() != null
						&& castOther.getApplicantAtttitude() != null && this
						.getApplicantAtttitude().equals(
								castOther.getApplicantAtttitude())))
				&& ((this.getInterviewComments() == castOther
						.getInterviewComments()) || (this
						.getInterviewComments() != null
						&& castOther.getInterviewComments() != null && this
						.getInterviewComments().equals(
								castOther.getInterviewComments())))
				&& ((this.getFormalInterviewComplete() == castOther
						.getFormalInterviewComplete()) || (this
						.getFormalInterviewComplete() != null
						&& castOther.getFormalInterviewComplete() != null && this
						.getFormalInterviewComplete().equals(
								castOther.getFormalInterviewComplete())))
				&& ((this.getAge() == castOther.getAge()) || (this.getAge() != null
						&& castOther.getAge() != null && this.getAge().equals(
						castOther.getAge())))
				&& ((this.getDateOfBirth() == castOther.getDateOfBirth()) || (this
						.getDateOfBirth() != null
						&& castOther.getDateOfBirth() != null && this
						.getDateOfBirth().equals(castOther.getDateOfBirth())))
				&& ((this.getExpiryDateOfPassport() == castOther
						.getExpiryDateOfPassport()) || (this
						.getExpiryDateOfPassport() != null
						&& castOther.getExpiryDateOfPassport() != null && this
						.getExpiryDateOfPassport().equals(
								castOther.getExpiryDateOfPassport())))
				&& ((this.getWorkPermitValidity() == castOther
						.getWorkPermitValidity()) || (this
						.getWorkPermitValidity() != null
						&& castOther.getWorkPermitValidity() != null && this
						.getWorkPermitValidity().equals(
								castOther.getWorkPermitValidity())))
				&& ((this.getCellNumber() == castOther.getCellNumber()) || (this
						.getCellNumber() != null
						&& castOther.getCellNumber() != null && this
						.getCellNumber().equals(castOther.getCellNumber())))
				&& ((this.getEMail() == castOther.getEMail()) || (this
						.getEMail() != null && castOther.getEMail() != null && this
						.getEMail().equals(castOther.getEMail())))
				&& ((this.getJobType() == castOther.getJobType()) || (this
						.getJobType() != null && castOther.getJobType() != null && this
						.getJobType().equals(castOther.getJobType())))
				&& ((this.getDriversLicenseVerified() == castOther
						.getDriversLicenseVerified()) || (this
						.getDriversLicenseVerified() != null
						&& castOther.getDriversLicenseVerified() != null && this
						.getDriversLicenseVerified().equals(
								castOther.getDriversLicenseVerified())))
				&& ((this.getDateFirstIssueLicense() == castOther
						.getDateFirstIssueLicense()) || (this
						.getDateFirstIssueLicense() != null
						&& castOther.getDateFirstIssueLicense() != null && this
						.getDateFirstIssueLicense().equals(
								castOther.getDateFirstIssueLicense())))
				&& ((this.getLicenseCode() == castOther.getLicenseCode()) || (this
						.getLicenseCode() != null
						&& castOther.getLicenseCode() != null && this
						.getLicenseCode().equals(castOther.getLicenseCode())))
				&& ((this.getExpiryDateOfLicense() == castOther
						.getExpiryDateOfLicense()) || (this
						.getExpiryDateOfLicense() != null
						&& castOther.getExpiryDateOfLicense() != null && this
						.getExpiryDateOfLicense().equals(
								castOther.getExpiryDateOfLicense())))
				&& ((this.getPdpExpiryDate() == castOther.getPdpExpiryDate()) || (this
						.getPdpExpiryDate() != null
						&& castOther.getPdpExpiryDate() != null && this
						.getPdpExpiryDate()
						.equals(castOther.getPdpExpiryDate())))
				&& ((this.getGender() == castOther.getGender()) || (this
						.getGender() != null && castOther.getGender() != null && this
						.getGender().equals(castOther.getGender())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null
						&& castOther.getCity() != null && this.getCity()
						.equals(castOther.getCity())))
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())))
				&& ((this.getHomeLanguage() == castOther.getHomeLanguage()) || (this
						.getHomeLanguage() != null
						&& castOther.getHomeLanguage() != null && this
						.getHomeLanguage().equals(castOther.getHomeLanguage())))
				&& ((this.getLastSmsDate() == castOther.getLastSmsDate()) || (this
						.getLastSmsDate() != null
						&& castOther.getLastSmsDate() != null && this
						.getLastSmsDate().equals(castOther.getLastSmsDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMacApplicants();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getSurname() == null ? 0 : this.getSurname().hashCode());
		result = 37 * result
				+ (getJobName() == null ? 0 : this.getJobName().hashCode());
		result = 37
				* result
				+ (getRsaCitizen() == null ? 0 : this.getRsaCitizen()
						.hashCode());
		result = 37 * result
				+ (getIdNumber() == null ? 0 : this.getIdNumber().hashCode());
		result = 37
				* result
				+ (getIdVerified() == null ? 0 : this.getIdVerified()
						.hashCode());
		result = 37 * result
				+ (getSapCheck() == null ? 0 : this.getSapCheck().hashCode());
		result = 37
				* result
				+ (getCriminalRecord() == null ? 0 : this.getCriminalRecord()
						.hashCode());
		result = 37
				* result
				+ (getCriminalRecordComments() == null ? 0 : this
						.getCriminalRecordComments().hashCode());
		result = 37
				* result
				+ (getWorkHistoryVerified() == null ? 0 : this
						.getWorkHistoryVerified().hashCode());
		result = 37
				* result
				+ (getUnionMember() == null ? 0 : this.getUnionMember()
						.hashCode());
		result = 37 * result
				+ (getUnionName() == null ? 0 : this.getUnionName().hashCode());
		result = 37
				* result
				+ (getApplicantPassedInterview() == null ? 0 : this
						.getApplicantPassedInterview().hashCode());
		result = 37
				* result
				+ (getApplicantPresentable() == null ? 0 : this
						.getApplicantPresentable().hashCode());
		result = 37
				* result
				+ (getApplicantAtttitude() == null ? 0 : this
						.getApplicantAtttitude().hashCode());
		result = 37
				* result
				+ (getInterviewComments() == null ? 0 : this
						.getInterviewComments().hashCode());
		result = 37
				* result
				+ (getFormalInterviewComplete() == null ? 0 : this
						.getFormalInterviewComplete().hashCode());
		result = 37 * result
				+ (getAge() == null ? 0 : this.getAge().hashCode());
		result = 37
				* result
				+ (getDateOfBirth() == null ? 0 : this.getDateOfBirth()
						.hashCode());
		result = 37
				* result
				+ (getExpiryDateOfPassport() == null ? 0 : this
						.getExpiryDateOfPassport().hashCode());
		result = 37
				* result
				+ (getWorkPermitValidity() == null ? 0 : this
						.getWorkPermitValidity().hashCode());
		result = 37
				* result
				+ (getCellNumber() == null ? 0 : this.getCellNumber()
						.hashCode());
		result = 37 * result
				+ (getEMail() == null ? 0 : this.getEMail().hashCode());
		result = 37 * result
				+ (getJobType() == null ? 0 : this.getJobType().hashCode());
		result = 37
				* result
				+ (getDriversLicenseVerified() == null ? 0 : this
						.getDriversLicenseVerified().hashCode());
		result = 37
				* result
				+ (getDateFirstIssueLicense() == null ? 0 : this
						.getDateFirstIssueLicense().hashCode());
		result = 37
				* result
				+ (getLicenseCode() == null ? 0 : this.getLicenseCode()
						.hashCode());
		result = 37
				* result
				+ (getExpiryDateOfLicense() == null ? 0 : this
						.getExpiryDateOfLicense().hashCode());
		result = 37
				* result
				+ (getPdpExpiryDate() == null ? 0 : this.getPdpExpiryDate()
						.hashCode());
		result = 37 * result
				+ (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37 * result
				+ (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37
				* result
				+ (getHomeLanguage() == null ? 0 : this.getHomeLanguage()
						.hashCode());
		result = 37
				* result
				+ (getLastSmsDate() == null ? 0 : this.getLastSmsDate()
						.hashCode());
		return result;
	}

}
