package aoc.Harlequin.OBJs;

// Generated 13 Jul 2018 2:39:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * BlockedNumberList generated by hbm2java
 */
public class BlockedNumberList implements java.io.Serializable {

	private Integer idBlockedNumberList;
	private String cellNumber;
	private String dateBlocked;

	public BlockedNumberList() {
	}

	public BlockedNumberList(String cellNumber) {
		this.cellNumber = cellNumber;
	}

	public BlockedNumberList(String cellNumber, String dateBlocked) {
		this.cellNumber = cellNumber;
		this.dateBlocked = dateBlocked;
	}

	public Integer getIdBlockedNumberList() {
		return this.idBlockedNumberList;
	}

	public void setIdBlockedNumberList(Integer idBlockedNumberList) {
		this.idBlockedNumberList = idBlockedNumberList;
	}

	public String getCellNumber() {
		return this.cellNumber;
	}

	public void setCellNumber(String cellNumber) {
		this.cellNumber = cellNumber;
	}

	public String getDateBlocked() {
		return this.dateBlocked;
	}

	public void setDateBlocked(String dateBlocked) {
		this.dateBlocked = dateBlocked;
	}

}
