package aoc.Harlequin.OBJs;

// Generated 21 May 2018 5:16:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClientInterviews generated by hbm2java
 */
public class ClientInterviews implements java.io.Serializable {

	private int idClientInterviews;
	private Integer idMacApplicants;
	private String clientName;
	private String applicantName;
	private String applicantSurname;
	private String interviewQuestionsPassed;
	private String applicantPresentable;
	private String applicantAttitude;
	private String interviewComments;
	private String clientInterviewComplete;

	public ClientInterviews() {
	}

	public ClientInterviews(int idClientInterviews) {
		this.idClientInterviews = idClientInterviews;
	}

	public ClientInterviews(int idClientInterviews, Integer idMacApplicants,
			String clientName, String applicantName, String applicantSurname,
			String interviewQuestionsPassed, String applicantPresentable,
			String applicantAttitude, String interviewComments,
			String clientInterviewComplete) {
		this.idClientInterviews = idClientInterviews;
		this.idMacApplicants = idMacApplicants;
		this.clientName = clientName;
		this.applicantName = applicantName;
		this.applicantSurname = applicantSurname;
		this.interviewQuestionsPassed = interviewQuestionsPassed;
		this.applicantPresentable = applicantPresentable;
		this.applicantAttitude = applicantAttitude;
		this.interviewComments = interviewComments;
		this.clientInterviewComplete = clientInterviewComplete;
	}

	public int getIdClientInterviews() {
		return this.idClientInterviews;
	}

	public void setIdClientInterviews(int idClientInterviews) {
		this.idClientInterviews = idClientInterviews;
	}

	public Integer getIdMacApplicants() {
		return this.idMacApplicants;
	}

	public void setIdMacApplicants(Integer idMacApplicants) {
		this.idMacApplicants = idMacApplicants;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getApplicantName() {
		return this.applicantName;
	}

	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}

	public String getApplicantSurname() {
		return this.applicantSurname;
	}

	public void setApplicantSurname(String applicantSurname) {
		this.applicantSurname = applicantSurname;
	}

	public String getInterviewQuestionsPassed() {
		return this.interviewQuestionsPassed;
	}

	public void setInterviewQuestionsPassed(String interviewQuestionsPassed) {
		this.interviewQuestionsPassed = interviewQuestionsPassed;
	}

	public String getApplicantPresentable() {
		return this.applicantPresentable;
	}

	public void setApplicantPresentable(String applicantPresentable) {
		this.applicantPresentable = applicantPresentable;
	}

	public String getApplicantAttitude() {
		return this.applicantAttitude;
	}

	public void setApplicantAttitude(String applicantAttitude) {
		this.applicantAttitude = applicantAttitude;
	}

	public String getInterviewComments() {
		return this.interviewComments;
	}

	public void setInterviewComments(String interviewComments) {
		this.interviewComments = interviewComments;
	}

	public String getClientInterviewComplete() {
		return this.clientInterviewComplete;
	}

	public void setClientInterviewComplete(String clientInterviewComplete) {
		this.clientInterviewComplete = clientInterviewComplete;
	}

}
