package aoc.Harlequin.OBJs;

import java.util.Collection;

// Generated 19 Mar 2018 10:38:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * MacApplicants generated by hbm2java
 */
public class MacApplicants implements java.io.Serializable {

	private Integer idMacApplicants;
	private String name;
	private String surname;
	private String rsaCitizen;
	private String Id_Number;
	private String workPermitValidity;
	private String cellNumber;
	private String telephoneNumber;
	private String jobType;
	private String dateFirstIssueLicense;
	private String licenseCode;
	private String expiryDateOfLicense;
	private String pdpExpiryDate;
	private String gender;
	private String physicalAddress1;
	private String physicalAddress2;
	private String physicalAddress3;
	private String physicalAddress4;
	private String maritalStatus;
	private String dependants;
	private String homeLanguage;
	private String workHistory1;
	private String workHistory2;
	private String workHistory3;
	private String workHistory4;
	private String email;
	private String passportNumber;
	private String expiryDateOfPassport;

	public MacApplicants() {
	}

	public MacApplicants(String name, String surname, String rsaCitizen,
			String Id_Number, String workPermitValidity, String cellNumber,
			String telephoneNumber, String jobType,
			String dateFirstIssueLicense, String licenseCode,
			String expiryDateOfLicense, String pdpExpiryDate, String gender,
			String physicalAddress1, String physicalAddress2,
			String physicalAddress3, String physicalAddress4,
			String maritalStatus, String dependants, String homeLanguage,
			String workHistory1, String workHistory2, String workHistory3,
			String workHistory4, String email, String passportNumber,String expiryDateOfPassport) {
		this.name = name;
		this.surname = surname;
		this.rsaCitizen = rsaCitizen;
		this.Id_Number = Id_Number;
		this.workPermitValidity = workPermitValidity;
		this.cellNumber = cellNumber;
		this.telephoneNumber = telephoneNumber;
		this.jobType = jobType;
		this.dateFirstIssueLicense = dateFirstIssueLicense;
		this.licenseCode = licenseCode;
		this.expiryDateOfLicense = expiryDateOfLicense;
		this.pdpExpiryDate = pdpExpiryDate;
		this.gender = gender;
		this.physicalAddress1 = physicalAddress1;
		this.physicalAddress2 = physicalAddress2;
		this.physicalAddress3 = physicalAddress3;
		this.physicalAddress4 = physicalAddress4;
		this.maritalStatus = maritalStatus;
		this.dependants = dependants;
		this.homeLanguage = homeLanguage;
		this.workHistory1 = workHistory1;
		this.workHistory2 = workHistory2;
		this.workHistory3 = workHistory3;
		this.workHistory4 = workHistory4;
		this.email = email;
		this.expiryDateOfPassport = expiryDateOfPassport;
	}

	public Integer getIdMacApplicants() {
		return this.idMacApplicants;
	}

	public void setIdMacApplicants(Integer idMacApplicants) {
		this.idMacApplicants = idMacApplicants;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getRsaCitizen() {
		return this.rsaCitizen;
	}

	public void setRsaCitizen(String rsaCitizen) {
		this.rsaCitizen = rsaCitizen;
	}

	public String getIdNumber() {
		return this.Id_Number;
	}

	public void setIdNumber(String Id_Number) {
		this.Id_Number = Id_Number;
	}

	public String getWorkPermitValidity() {
		return this.workPermitValidity;
	}

	public void setWorkPermitValidity(String workPermitValidity) {
		this.workPermitValidity = workPermitValidity;
	}

	public String getCellNumber() {
		return this.cellNumber;
	}

	public void setCellNumber(String cellNumber) {
		this.cellNumber = cellNumber;
	}

	public String getTelephoneNumber() {
		return this.telephoneNumber;
	}

	public void setTelephoneNumber(String telephoneNumber) {
		this.telephoneNumber = telephoneNumber;
	}

	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	public String getDateFirstIssueLicense() {
		return this.dateFirstIssueLicense;
	}

	public void setDateFirstIssueLicense(String dateFirstIssueLicense) {
		this.dateFirstIssueLicense = dateFirstIssueLicense;
	}

	public String getLicenseCode() {
		return this.licenseCode;
	}

	public void setLicenseCode(String licenseCode) {
		this.licenseCode = licenseCode;
	}

	public String getExpiryDateOfLicense() {
		return this.expiryDateOfLicense;
	}
	
	public String getEmail() {
		return this.email;
	}
	
	public String getPassportNumber() {
		return this.passportNumber;
	}
	
	

	
	public String getExpiryDateOfPassport() {
		return this.expiryDateOfPassport;
	}
	
	public void setExpiryDateOfPassport(String expiryDateOfPassport) {
		this.expiryDateOfPassport = expiryDateOfPassport;
	}
	
	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}
	
	public void setExpiryDateOfLicense(String expiryDateOfLicense) {
		this.expiryDateOfLicense = expiryDateOfLicense;
	}

	public String getPdpExpiryDate() {
		return this.pdpExpiryDate;
	}

	public void setPdpExpiryDate(String pdpExpiryDate) {
		this.pdpExpiryDate = pdpExpiryDate;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPhysicalAddress1() {
		return this.physicalAddress1;
	}

	public void setPhysicalAddress1(String physicalAddress1) {
		this.physicalAddress1 = physicalAddress1;
	}

	public String getPhysicalAddress2() {
		return this.physicalAddress2;
	}

	public void setPhysicalAddress2(String physicalAddress2) {
		this.physicalAddress2 = physicalAddress2;
	}

	public String getPhysicalAddress3() {
		return this.physicalAddress3;
	}

	public void setPhysicalAddress3(String physicalAddress3) {
		this.physicalAddress3 = physicalAddress3;
	}

	public String getPhysicalAddress4() {
		return this.physicalAddress4;
	}

	public void setPhysicalAddress4(String physicalAddress4) {
		this.physicalAddress4 = physicalAddress4;
	}

	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getDependants() {
		return this.dependants;
	}

	public void setDependants(String dependants) {
		this.dependants = dependants;
	}

	public String getHomeLanguage() {
		return this.homeLanguage;
	}

	public void setHomeLanguage(String homeLanguage) {
		this.homeLanguage = homeLanguage;
	}

	public String getWorkHistory1() {
		return this.workHistory1;
	}

	public void setWorkHistory1(String workHistory1) {
		this.workHistory1 = workHistory1;
	}

	public String getWorkHistory2() {
		return this.workHistory2;
	}

	public void setWorkHistory2(String workHistory2) {
		this.workHistory2 = workHistory2;
	}

	public String getWorkHistory3() {
		return this.workHistory3;
	}

	public void setWorkHistory3(String workHistory3) {
		this.workHistory3 = workHistory3;
	}

	public String getWorkHistory4() {
		return this.workHistory4;
	}

	public void setWorkHistory4(String workHistory4) {
		this.workHistory4 = workHistory4;
	}

	public void setEmail(String email) {
		// TODO Auto-generated method stub
		this.email = email;
		
	}

	

	

}
