package aoc.Harlequin.OBJs;

// Generated 21 May 2018 11:40:36 AM by Hibernate Tools 3.4.0.CR1

/**
 * MacLabourInterView generated by hbm2java
 */
public class MacLabourInterView implements java.io.Serializable {

	private int idMacLabourInterView;
	private Integer idMacApplicants;
	private String name;
	private String surname;
	private String idNumber;
	private String clientName;
	private String idVerified;
	private String workHistoryVerified;
	private String jobName;
	private String driversLicenseVerified;
	private String sapCheck;
	private String criminalRecord;
	private String criminalRecordComments;
	private String unionMember;
	private String unionName;
	private String applicantPassedInterview;
	private String applicantPresentable;
	private String applicantAtttitude;
	private String interviewComments;
	private String formalInterviewComplete;
	
	private String lastUsedDate;
	private String passed;

	public MacLabourInterView() {
	}

	public MacLabourInterView(int idMacLabourInterView) {
		this.idMacLabourInterView = idMacLabourInterView;
	}

	public MacLabourInterView(int idMacLabourInterView,
			Integer idMacApplicants, String name, String surname,
			String idNumber, String clientName, String idVerified,
			String workHistoryVerified, String jobName,
			String driversLicenseVerified, String sapCheck,
			String criminalRecord, String criminalRecordComments,
			String unionMember, String unionName,
			String applicantPassedInterview, String applicantPresentable,
			String applicantAtttitude, String interviewComments,
			String formalInterviewComplete, String lastUsedDate,
			String passed) {
		this.idMacLabourInterView = idMacLabourInterView;
		this.idMacApplicants = idMacApplicants;
		this.name = name;
		this.surname = surname;
		this.idNumber = idNumber;
		this.clientName = clientName;
		this.idVerified = idVerified;
		this.workHistoryVerified = workHistoryVerified;
		this.jobName = jobName;
		this.driversLicenseVerified = driversLicenseVerified;
		this.sapCheck = sapCheck;
		this.criminalRecord = criminalRecord;
		this.criminalRecordComments = criminalRecordComments;
		this.unionMember = unionMember;
		this.unionName = unionName;
		this.applicantPassedInterview = applicantPassedInterview;
		this.applicantPresentable = applicantPresentable;
		this.applicantAtttitude = applicantAtttitude;
		this.interviewComments = interviewComments;
		this.formalInterviewComplete = formalInterviewComplete;
		this.lastUsedDate = lastUsedDate;
		this.passed = passed;
	}

	
	public String getPassed() 
	{
		return this.passed;
	}

	public void setPassed(String passed) 
	{
		this.passed = passed;
	}
	
	public String getLastUsedDate() 
	{
		return this.lastUsedDate;
	}

	public void setLastUsedDate(String lastUsedDate) 
	{
		this.lastUsedDate = lastUsedDate;
	}
	
	public int getIdMacLabourInterView() 
	{
		return this.idMacLabourInterView;
	}

	public void setIdMacLabourInterView(int idMacLabourInterView) {
		this.idMacLabourInterView = idMacLabourInterView;
	}

	public Integer getIdMacApplicants() {
		return this.idMacApplicants;
	}

	public void setIdMacApplicants(Integer idMacApplicants) {
		this.idMacApplicants = idMacApplicants;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getIdVerified() {
		return this.idVerified;
	}

	public void setIdVerified(String idVerified) {
		this.idVerified = idVerified;
	}

	public String getWorkHistoryVerified() {
		return this.workHistoryVerified;
	}

	public void setWorkHistoryVerified(String workHistoryVerified) {
		this.workHistoryVerified = workHistoryVerified;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getDriversLicenseVerified() {
		return this.driversLicenseVerified;
	}

	public void setDriversLicenseVerified(String driversLicenseVerified) {
		this.driversLicenseVerified = driversLicenseVerified;
	}

	public String getSapCheck() {
		return this.sapCheck;
	}

	public void setSapCheck(String sapCheck) {
		this.sapCheck = sapCheck;
	}

	public String getCriminalRecord() {
		return this.criminalRecord;
	}

	public void setCriminalRecord(String criminalRecord) {
		this.criminalRecord = criminalRecord;
	}

	public String getCriminalRecordComments() {
		return this.criminalRecordComments;
	}

	public void setCriminalRecordComments(String criminalRecordComments) {
		this.criminalRecordComments = criminalRecordComments;
	}

	public String getUnionMember() {
		return this.unionMember;
	}

	public void setUnionMember(String unionMember) {
		this.unionMember = unionMember;
	}

	public String getUnionName() {
		return this.unionName;
	}

	public void setUnionName(String unionName) {
		this.unionName = unionName;
	}

	public String getApplicantPassedInterview() {
		return this.applicantPassedInterview;
	}

	public void setApplicantPassedInterview(String applicantPassedInterview) {
		this.applicantPassedInterview = applicantPassedInterview;
	}

	public String getApplicantPresentable() {
		return this.applicantPresentable;
	}

	public void setApplicantPresentable(String applicantPresentable) {
		this.applicantPresentable = applicantPresentable;
	}

	public String getApplicantAtttitude() {
		return this.applicantAtttitude;
	}

	public void setApplicantAtttitude(String applicantAtttitude) {
		this.applicantAtttitude = applicantAtttitude;
	}

	public String getInterviewComments() {
		return this.interviewComments;
	}

	public void setInterviewComments(String interviewComments) {
		this.interviewComments = interviewComments;
	}

	public String getFormalInterviewComplete() {
		return this.formalInterviewComplete;
	}

	public void setFormalInterviewComplete(String formalInterviewComplete) {
		this.formalInterviewComplete = formalInterviewComplete;
	}

}
