package aoc.Harlequin.OBJs;

// Generated 06 Mar 2018 11:04:37 AM by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class overideuser implements java.io.Serializable {

	private Integer idoverideUser;
	private String Name;
	private String Surname;
	private String Password;
	

	public overideuser() {
	}

	public overideuser(int idoverideUser, String Name, String Surname, String Password) {
		this.idoverideUser = idoverideUser;
		this.Name = Name;
		this.Surname = Surname;
		this.Password = Password;
	}

	public Integer getIdoverideUser() {
		return this.idoverideUser;
	}

	public void setIdoverideUser(Integer idoverideUser) {
		this.idoverideUser = idoverideUser;
	}

	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	
	public String getSurname() {
		return this.Surname;
	}
	
	
	
	public String getPassword() {
		return this.Password;
	}

	public void setPassword(String Password) {
		this.Password = Password;
	}

}
