package aoc.Harlequin.OBJs;

// Generated 07 May 2018 11:58:04 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * PracticalDriversAssessment generated by hbm2java
 */
public class PracticalDriversAssessment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPracticalDriversAssessment;
	private Integer idMacApplicants;
	private String name;
	private String surname;
	private String idNumber;
	private String clientName;
	private String pdpExpiryDate;
	private String vehicleUsed;
	private String assessorName;
	private String assessorSurname;
	private Integer assessorUserId;
	private String date;
	private String kmEnd;
	private String kmStart;
	private String timeEnd;
	private String timeStart;
	private String weather;
	private String route;
	private BigDecimal totalScore;
	private BigDecimal startingAndStopping;
	private BigDecimal generalDriving;
	private BigDecimal passingOrOvertaking;
	private BigDecimal generalRoadBehavior;
	private BigDecimal observationAndAnticipation;
	private BigDecimal approachingJunctionsTurningExiting;
	private BigDecimal reversing;
	private BigDecimal clutch;
	private BigDecimal retarderDscHillMode;
	private String comments;
	private Integer pdaNo;
	private String licenseCode;
	private String practicalDriversTestComplete;
	private String practicalDriversTestComments;
	private String jobName;
	private String lastUsedDate;
	
	private String StartingAndStopping1;
	private String StartingAndStopping2;
	private String StartingAndStopping3;
	private String StartingAndStopping4;
	private String StartingAndStopping5;
	private String StartingAndStopping6;
	private String StartingAndStopping7;
	
	private String GeneralDriving8;
	private String GeneralDriving9;
	private String GeneralDriving10;
	private String GeneralDriving11;
	private String GeneralDriving12;
	private String GeneralDriving13;
	private String GeneralDriving14;
	private String GeneralDriving15;
	private String GeneralDriving16;
	private String GeneralDriving17;
	
	private String PassingOrOvertaking18;
	private String PassingOrOvertaking19;
	private String PassingOrOvertaking20;
	private String PassingOrOvertaking21;
	
	private String GeneralRoadBehavior22;
	private String GeneralRoadBehavior23;
	
	private String ObservationAndAnticipation24;
	private String ObservationAndAnticipation25;
	private String ObservationAndAnticipation26;
	private String ObservationAndAnticipation27;
	private String ObservationAndAnticipation28;
	
	private String ApproachingJunctionsTurningExiting29;
	private String ApproachingJunctionsTurningExiting30;
	private String ApproachingJunctionsTurningExiting31;
	private String ApproachingJunctionsTurningExiting32;
	private String ApproachingJunctionsTurningExiting33;
	private String ApproachingJunctionsTurningExiting34;
	private String ApproachingJunctionsTurningExiting35;
	private String ApproachingJunctionsTurningExiting36;
	
	private String Reversing37;
	private String Reversing38;
	private String Reversing39;
	
	private String Clutch40;
	private String Clutch41;
	
	private String RetarderDSCHillMode42;
	private String RetarderDSCHillMode43;
	private String RetarderDSCHillMode44;


	public PracticalDriversAssessment() 
	{
		
	}

	public PracticalDriversAssessment(int idPracticalDriversAssessment) 
	{
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
	}

	public PracticalDriversAssessment(int idPracticalDriversAssessment,
			Integer idMacApplicants, String name, String surname,
			String idNumber, String clientName, String pdpExpiryDate,
			String vehicleUsed, String assessorName, String assessorSurname,
			Integer assessorUserId, String date, String kmEnd, String kmStart,
			String timeEnd, String timeStart, String weather, String route,
			BigDecimal totalScore, BigDecimal startingAndStopping,
			BigDecimal generalDriving, BigDecimal passingOrOvertaking,
			BigDecimal generalRoadBehavior,
			BigDecimal observationAndAnticipation,
			BigDecimal approachingJunctionsTurningExiting,
			BigDecimal reversing, BigDecimal clutch,
			BigDecimal retarderDscHillMode, String comments, Integer pdaNo,
			String licenseCode,String practicalDriversTestComplete,String practicalDriversTestComments,
			String jobName, String lastUsedDate,
			String StartingAndStopping1, String StartingAndStopping2, String StartingAndStopping3, String StartingAndStopping4, String StartingAndStopping5, String StartingAndStopping6, String StartingAndStopping7,
			String GeneralDriving8, String GeneralDriving9, String GeneralDriving10, String GeneralDriving11, String GeneralDriving12, String GeneralDriving13, String GeneralDriving14, String GeneralDriving15, String GeneralDriving16, String GeneralDriving17,
			String PassingOrOvertaking18, String PassingOrOvertaking19, String PassingOrOvertaking20, String PassingOrOvertaking21,
			String GeneralRoadBehavior22, String GeneralRoadBehavior23,
			String ObservationAndAnticipation24, String ObservationAndAnticipation25, String ObservationAndAnticipation26, String ObservationAndAnticipation27,  String ObservationAndAnticipation28,
			String ApproachingJunctionsTurningExiting29,String ApproachingJunctionsTurningExiting30, String ApproachingJunctionsTurningExiting31,String ApproachingJunctionsTurningExiting32, String ApproachingJunctionsTurningExiting33, String ApproachingJunctionsTurningExiting34, String ApproachingJunctionsTurningExiting35,String ApproachingJunctionsTurningExiting36,
			String Reversing37, String Reversing38, String Reversing39,
			String Clutch40, String Clutch41,
			String RetarderDSCHillMode42, String RetarderDSCHillMode43, String RetarderDSCHillMode44) {
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
		this.idMacApplicants = idMacApplicants;
		this.name = name;
		this.surname = surname;
		this.idNumber = idNumber;
		this.clientName = clientName;
		this.pdpExpiryDate = pdpExpiryDate;
		this.vehicleUsed = vehicleUsed;
		this.assessorName = assessorName;
		this.assessorSurname = assessorSurname;
		this.assessorUserId = assessorUserId;
		this.date = date;
		this.kmEnd = kmEnd;
		this.kmStart = kmStart;
		this.timeEnd = timeEnd;
		this.timeStart = timeStart;
		this.weather = weather;
		this.route = route;
		this.totalScore = totalScore;
		this.startingAndStopping = startingAndStopping;
		this.generalDriving = generalDriving;
		this.passingOrOvertaking = passingOrOvertaking;
		this.generalRoadBehavior = generalRoadBehavior;
		this.observationAndAnticipation = observationAndAnticipation;
		this.approachingJunctionsTurningExiting = approachingJunctionsTurningExiting;
		this.reversing = reversing;
		this.clutch = clutch;
		this.retarderDscHillMode = retarderDscHillMode;
		this.comments = comments;
		this.pdaNo = pdaNo;
		this.licenseCode = licenseCode;
		this.practicalDriversTestComplete = practicalDriversTestComplete;
		this.practicalDriversTestComments = practicalDriversTestComments;
		this.jobName = jobName;
		this.lastUsedDate = lastUsedDate;
		
		this.StartingAndStopping1 = StartingAndStopping1; 
		this.StartingAndStopping2 = StartingAndStopping2;
		this.StartingAndStopping3 = StartingAndStopping3; 
		this.StartingAndStopping4 = StartingAndStopping4;
		this.StartingAndStopping5 = StartingAndStopping5; 
		this.StartingAndStopping6 = StartingAndStopping6;
		this.StartingAndStopping7 = StartingAndStopping7;
		
		this.GeneralDriving8 = GeneralDriving8;
		this.GeneralDriving9 = GeneralDriving9;
		this.GeneralDriving10 = GeneralDriving10;
		this.GeneralDriving11 = GeneralDriving11;
		this.GeneralDriving12 = GeneralDriving12;
		this.GeneralDriving13 = GeneralDriving13;
		this.GeneralDriving14 = GeneralDriving14;
		this.GeneralDriving15 = GeneralDriving15;
		this.GeneralDriving16 = GeneralDriving16;
		this.GeneralDriving17 = GeneralDriving17;
		
		this.PassingOrOvertaking18 = PassingOrOvertaking18;
		this.PassingOrOvertaking19 = PassingOrOvertaking19;
		this.PassingOrOvertaking20 = PassingOrOvertaking20;
		this.PassingOrOvertaking21 = PassingOrOvertaking21;
		
		
		this.GeneralRoadBehavior22 = GeneralRoadBehavior22;
		this.GeneralRoadBehavior23 = GeneralRoadBehavior23;
		
		this.ObservationAndAnticipation24 = ObservationAndAnticipation24;
		this.ObservationAndAnticipation25 = ObservationAndAnticipation25;
		this.ObservationAndAnticipation26 = ObservationAndAnticipation26;
		this.ObservationAndAnticipation27 = ObservationAndAnticipation27;
		this.ObservationAndAnticipation28 = ObservationAndAnticipation28;
		
		
		this.ApproachingJunctionsTurningExiting29 = ApproachingJunctionsTurningExiting29;
		this.ApproachingJunctionsTurningExiting30 = ApproachingJunctionsTurningExiting30;
		this.ApproachingJunctionsTurningExiting31 = ApproachingJunctionsTurningExiting31;
		this.ApproachingJunctionsTurningExiting32 = ApproachingJunctionsTurningExiting32;
		this.ApproachingJunctionsTurningExiting33 = ApproachingJunctionsTurningExiting33;
		this.ApproachingJunctionsTurningExiting34 = ApproachingJunctionsTurningExiting34;
		this.ApproachingJunctionsTurningExiting35 = ApproachingJunctionsTurningExiting35;
		this.ApproachingJunctionsTurningExiting36 = ApproachingJunctionsTurningExiting36;
		
		this.Reversing37 = Reversing37;
		this.Reversing38 = Reversing38;
		this.Reversing39 = Reversing39;
		
		this.Clutch40 = Clutch40;
		this.Clutch41 = Clutch41;
		
		this.RetarderDSCHillMode42 = RetarderDSCHillMode42;
		this.RetarderDSCHillMode43 = RetarderDSCHillMode43;
		this.RetarderDSCHillMode44 = RetarderDSCHillMode44; 
		
		
		
		
		
	}

	
	
	public String getLastUsedDate()
	{
		return this.lastUsedDate;
	}

	public void setLastUsedDate(String lastUsedDate) 
	{
		this.lastUsedDate = lastUsedDate;
	}
	
	public String getjobName()
	{
		return this.jobName;
	}

	public void setjobName(String jobName) 
	{
		this.jobName = jobName;
	}
	
	
	
	public int getIdPracticalDriversAssessment()
	{
		return this.idPracticalDriversAssessment;
	}

	public void setIdPracticalDriversAssessment(int idPracticalDriversAssessment) 
	{
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
	}

	public Integer getIdMacApplicants() 
	{
		return this.idMacApplicants;
	}

	public void setIdMacApplicants(Integer idMacApplicants) 
	{
		this.idMacApplicants = idMacApplicants;
	}

	public String getName() 
	{
		return this.name;
	}

	public void setName(String name) 
	{
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getPdpExpiryDate() {
		return this.pdpExpiryDate;
	}

	public void setPdpExpiryDate(String pdpExpiryDate) {
		this.pdpExpiryDate = pdpExpiryDate;
	}

	public String getVehicleUsed() {
		return this.vehicleUsed;
	}

	public void setVehicleUsed(String vehicleUsed) {
		this.vehicleUsed = vehicleUsed;
	}

	public String getAssessorName() {
		return this.assessorName;
	}

	public void setAssessorName(String assessorName) {
		this.assessorName = assessorName;
	}

	public String getAssessorSurname() {
		return this.assessorSurname;
	}

	public void setAssessorSurname(String assessorSurname) {
		this.assessorSurname = assessorSurname;
	}

	public Integer getAssessorUserId() {
		return this.assessorUserId;
	}

	public void setAssessorUserId(Integer assessorUserId) {
		this.assessorUserId = assessorUserId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getKmEnd() {
		return this.kmEnd;
	}

	public void setKmEnd(String kmEnd) {
		this.kmEnd = kmEnd;
	}

	public String getKmStart() {
		return this.kmStart;
	}

	public void setKmStart(String kmStart) {
		this.kmStart = kmStart;
	}

	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	public String getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	public String getWeather() {
		return this.weather;
	}

	public void setWeather(String weather) {
		this.weather = weather;
	}

	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	public BigDecimal getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(BigDecimal totalScore) {
		this.totalScore = totalScore;
	}

	public BigDecimal getStartingAndStopping() {
		return this.startingAndStopping;
	}

	public void setStartingAndStopping(BigDecimal startingAndStopping) {
		this.startingAndStopping = startingAndStopping;
	}

	public BigDecimal getGeneralDriving() {
		return this.generalDriving;
	}

	public void setGeneralDriving(BigDecimal generalDriving) {
		this.generalDriving = generalDriving;
	}

	public BigDecimal getPassingOrOvertaking() {
		return this.passingOrOvertaking;
	}

	public void setPassingOrOvertaking(BigDecimal passingOrOvertaking) {
		this.passingOrOvertaking = passingOrOvertaking;
	}

	public BigDecimal getGeneralRoadBehavior() {
		return this.generalRoadBehavior;
	}

	public void setGeneralRoadBehavior(BigDecimal generalRoadBehavior) {
		this.generalRoadBehavior = generalRoadBehavior;
	}

	public BigDecimal getObservationAndAnticipation() {
		return this.observationAndAnticipation;
	}

	public void setObservationAndAnticipation(
			BigDecimal observationAndAnticipation) {
		this.observationAndAnticipation = observationAndAnticipation;
	}

	public BigDecimal getApproachingJunctionsTurningExiting() {
		return this.approachingJunctionsTurningExiting;
	}

	public void setApproachingJunctionsTurningExiting(
			BigDecimal approachingJunctionsTurningExiting) {
		this.approachingJunctionsTurningExiting = approachingJunctionsTurningExiting;
	}

	public BigDecimal getReversing() {
		return this.reversing;
	}

	public void setReversing(BigDecimal reversing) {
		this.reversing = reversing;
	}

	public BigDecimal getClutch() {
		return this.clutch;
	}

	public void setClutch(BigDecimal clutch) {
		this.clutch = clutch;
	}

	public BigDecimal getRetarderDscHillMode() {
		return this.retarderDscHillMode;
	}

	public void setRetarderDscHillMode(BigDecimal retarderDscHillMode) {
		this.retarderDscHillMode = retarderDscHillMode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Integer getPdaNo() {
		return this.pdaNo;
	}

	public String getLicenseCode() {
		return this.licenseCode;
	}
	
	public void setPdaNo(Integer pdaNo) {
		this.pdaNo = pdaNo;
	}

	public void setLicenseCode(String license_Code) 
	{
		// TODO Auto-generated method stub
		this.licenseCode = license_Code;
	}
	
	

	public String getPracticalDriversTestComplete() 
	{
		return this.practicalDriversTestComplete;
	}

	public void setPracticalDriversTestComplete(String practicalDriversTestComplete) 
	{
		this.practicalDriversTestComplete = practicalDriversTestComplete;
	}

	
	public String getPracticalDriversTestComments() 
	{
		return this.practicalDriversTestComments;
	}

	public void setPracticalDriversTestComments(String practicalDriversTestComments) 
	{
		this.practicalDriversTestComments = practicalDriversTestComments;
	}
	
	
	
	public String getStartingAndStopping1() 
	{
		return this.StartingAndStopping1;
	}
	public void setStartingAndStopping1(String StartingAndStopping1) 
	{
		this.StartingAndStopping1 = StartingAndStopping1;
	}
	
	public String getStartingAndStopping2() 
	{
		return this.StartingAndStopping2;
	}
public void setStartingAndStopping2(String StartingAndStopping2) 
	{
		this.StartingAndStopping2 = StartingAndStopping2;
	}
	
	public String getStartingAndStopping3() 
	{
		return this.StartingAndStopping3;
	}
	public void setStartingAndStopping3(String StartingAndStopping3) 
	{
		this.StartingAndStopping3 = StartingAndStopping3;
	}
	
	public String getStartingAndStopping4() 
	{
		return this.StartingAndStopping4;
	}
	public void setStartingAndStopping4(String StartingAndStopping4) 
	{
		this.StartingAndStopping4 = StartingAndStopping4;
	}
	
	public String getStartingAndStopping5() 
	{
		return this.StartingAndStopping5;
	}
	public void setStartingAndStopping5(String StartingAndStopping5) 
	{
		this.StartingAndStopping5 = StartingAndStopping5;
	}
	
	public String getStartingAndStopping6() 
	{
		return this.StartingAndStopping6;
	}
	public void setStartingAndStopping6(String StartingAndStopping6) 
	{
		this.StartingAndStopping6 = StartingAndStopping6;
	}
	
	public String getStartingAndStopping7() 
	{
		return this.StartingAndStopping7;
	}
	public void setStartingAndStopping7(String StartingAndStopping7) 
	{
		this.StartingAndStopping7 = StartingAndStopping7;
	}
	
	
	public String getGeneralDriving8() 
	{
		return this.GeneralDriving8;
	}
	public void setGeneralDriving8(String GeneralDriving8) 
	{
		this.GeneralDriving8 = GeneralDriving8;
	}
	
	public String getGeneralDriving9() 
	{
		return this.GeneralDriving9;
	}
	public void setGeneralDriving9(String GeneralDriving9) 
	{
		this.GeneralDriving9 = GeneralDriving9;
	}

	public String getGeneralDriving10() 
	{
		return this.GeneralDriving10;
	}
	public void setGeneralDriving10(String GeneralDriving10) 
	{
		this.GeneralDriving10 = GeneralDriving10;
	}
	
	public String getGeneralDriving11() 
	{
		return this.GeneralDriving11;
	}
	public void setGeneralDriving11(String GeneralDriving11) 
	{
		this.GeneralDriving11 = GeneralDriving11;
	}
	
	public String getGeneralDriving12() 
	{
		return this.GeneralDriving12;
	}
	public void setGeneralDriving12(String GeneralDriving12) 
	{
		this.GeneralDriving12 = GeneralDriving12;
	}
	
	public String getGeneralDriving13() 
	{
		return this.GeneralDriving13;
	}
	public void setGeneralDriving13(String GeneralDriving13) 
	{
		this.GeneralDriving13 = GeneralDriving13;
	}
	
	public String getGeneralDriving14() 
	{
		return this.GeneralDriving14;
	}
	public void setGeneralDriving14(String GeneralDriving14) 
	{
		this.GeneralDriving14 = GeneralDriving14;
	}
	
	public String getGeneralDriving15() 
	{
		return this.GeneralDriving15;
	}
	public void setGeneralDriving15(String GeneralDriving15) 
	{
		this.GeneralDriving15 = GeneralDriving15;
	}
	
	public String getGeneralDriving16() 
	{
		return this.GeneralDriving16;
	}
	public void setGeneralDriving16(String GeneralDriving16) 
	{
		this.GeneralDriving16 = GeneralDriving16;
	}
	
	
	public String getGeneralDriving17() 
	{
		return this.GeneralDriving17;
	}
	public void setGeneralDriving17(String GeneralDriving17) 
	{
		this.GeneralDriving17 = GeneralDriving17;
	}
	
	
	public String getPassingOrOvertaking18() 
	{
		return this.PassingOrOvertaking18;
	}
	public void setPassingOrOvertaking18(String PassingOrOvertaking18) 
	{
		this.PassingOrOvertaking18 = PassingOrOvertaking18;
	}
	public String getPassingOrOvertaking19() 
	{
		return this.PassingOrOvertaking19;
	}
	public void setPassingOrOvertaking19(String PassingOrOvertaking19) 
	{
		this.PassingOrOvertaking19 = PassingOrOvertaking19;
	}
	public String getPassingOrOvertaking20() 
	{
		return this.PassingOrOvertaking20;
	}
	public void setPassingOrOvertaking20(String PassingOrOvertaking20) 
	{
		this.PassingOrOvertaking20 = PassingOrOvertaking20;
	}
	
	public String getPassingOrOvertaking21() 
	{
		return this.PassingOrOvertaking21;
	}
	public void setPassingOrOvertaking21(String PassingOrOvertaking21) 
	{
		this.PassingOrOvertaking21 = PassingOrOvertaking21;
	}
	
	public String getGeneralRoadBehavior22() 
	{
		return this.GeneralRoadBehavior22;
	}
	public void setGeneralRoadBehavior22(String GeneralRoadBehavior22) 
	{
		this.GeneralRoadBehavior22 = GeneralRoadBehavior22;
	}
	
	public String getGeneralRoadBehavior23() 
	{
		return this.GeneralRoadBehavior23;
	}
	public void setGeneralRoadBehavior23(String GeneralRoadBehavior23) 
	{
		this.GeneralRoadBehavior23 = GeneralRoadBehavior23;
	}
	
	public String getObservationAndAnticipation24() 
	{
		return this.ObservationAndAnticipation24;
	}
	public void setObservationAndAnticipation24(String ObservationAndAnticipation24) 
	{
		this.ObservationAndAnticipation24 = ObservationAndAnticipation24;
	}
	
	public String getObservationAndAnticipation25() 
	{
		return this.ObservationAndAnticipation25;
	}
	public void setObservationAndAnticipation25(String ObservationAndAnticipation25) 
	{
		this.ObservationAndAnticipation25 = ObservationAndAnticipation25;
	}
	
	public String getObservationAndAnticipation26() 
	{
		return this.ObservationAndAnticipation26;
	}
	public void setObservationAndAnticipation26(String ObservationAndAnticipation26) 
	{
		this.ObservationAndAnticipation26 = ObservationAndAnticipation26;
	}
	
	public String getObservationAndAnticipation27() 
	{
		return this.ObservationAndAnticipation27;
	}
	public void setObservationAndAnticipation27(String ObservationAndAnticipation27) 
	{
		this.ObservationAndAnticipation27 = ObservationAndAnticipation27;
	}
	
	public String getObservationAndAnticipation28() 
	{
		return this.ObservationAndAnticipation28;
	}
	public void setObservationAndAnticipation28(String ObservationAndAnticipation28) 
	{
		this.ObservationAndAnticipation28 = ObservationAndAnticipation28;
	}
	
	public String getApproachingJunctionsTurningExiting29() 
	{
		return this.ApproachingJunctionsTurningExiting29;
	}
	public void setApproachingJunctionsTurningExiting29(String ApproachingJunctionsTurningExiting29) 
	{
		this.ApproachingJunctionsTurningExiting29 = ApproachingJunctionsTurningExiting29;
	}
	
	
	public String getApproachingJunctionsTurningExiting30() 
	{
		return this.ApproachingJunctionsTurningExiting30;
	}
	public void setApproachingJunctionsTurningExiting30(String ApproachingJunctionsTurningExiting30) 
	{
		this.ApproachingJunctionsTurningExiting30 = ApproachingJunctionsTurningExiting30;
	}
	
	public String getApproachingJunctionsTurningExiting31() 
	{
		return this.ApproachingJunctionsTurningExiting31;
	}
	public void setApproachingJunctionsTurningExiting31(String ApproachingJunctionsTurningExiting31) 
	{
		this.ApproachingJunctionsTurningExiting31 = ApproachingJunctionsTurningExiting31;
	}
	
	public String getApproachingJunctionsTurningExiting32() 
	{
		return this.ApproachingJunctionsTurningExiting32;
	}
	public void setApproachingJunctionsTurningExiting32(String ApproachingJunctionsTurningExiting31) 
	{
		this.ApproachingJunctionsTurningExiting32 = ApproachingJunctionsTurningExiting32;
	}

	
	public String getApproachingJunctionsTurningExiting33() 
	{
		return this.ApproachingJunctionsTurningExiting33;
	}
	public void setApproachingJunctionsTurningExiting33(String ApproachingJunctionsTurningExiting33) 
	{
		this.ApproachingJunctionsTurningExiting33 = ApproachingJunctionsTurningExiting33;
	}
	
	public String getApproachingJunctionsTurningExiting34() 
	{
		return this.ApproachingJunctionsTurningExiting34;
	}
	public void setApproachingJunctionsTurningExiting34(String ApproachingJunctionsTurningExiting34) 
	{
		this.ApproachingJunctionsTurningExiting34 = ApproachingJunctionsTurningExiting34;
	}
	
	public String getApproachingJunctionsTurningExiting35() 
	{
		return this.ApproachingJunctionsTurningExiting35;
	}
	public void setApproachingJunctionsTurningExiting35(String ApproachingJunctionsTurningExiting35) 
	{
		this.ApproachingJunctionsTurningExiting35 = ApproachingJunctionsTurningExiting35;
	}
	
	public String getApproachingJunctionsTurningExiting36() 
	{
		return this.ApproachingJunctionsTurningExiting36;
	}
	public void setApproachingJunctionsTurningExiting36(String ApproachingJunctionsTurningExiting36) 
	{
		this.ApproachingJunctionsTurningExiting36 = ApproachingJunctionsTurningExiting36;
	}
	
	
	public String getReversing37() 
	{
		return this.Reversing37;
	}
	public void setReversing37(String Reversing37) 
	{
		this.Reversing37 = Reversing37;
	}
	public String getReversing38() 
	{
		return this.Reversing38;
	}
	public void setReversing38(String Reversing38) 
	{
		this.Reversing38 = Reversing38;
	}
	
	public String getReversing39() 
	{
		return this.Reversing39;
	}
	public void setReversing39(String Reversing39) 
	{
		this.Reversing39 = Reversing39;
	}
	
	public String getClutch40() 
	{
		return this.Clutch40;
	}
	public void setClutch40(String Clutch40) 
	{
		this.Clutch40 = Clutch40;
	}
	public String getClutch41() 
	{
		return this.Clutch41;
	}
	public void setClutch41(String Clutch41) 
	{
		this.Clutch41 = Clutch41;
	}
	
	
	public String getRetarderDSCHillMode42() 
	{
		return this.RetarderDSCHillMode42;
	}
	public void setRetarderDSCHillMode42(String RetarderDSCHillMode42) 
	{
		this.RetarderDSCHillMode42 = RetarderDSCHillMode42;
	}
	
	public String getRetarderDSCHillMode43() 
	{
		return this.RetarderDSCHillMode43;
	}
	public void setRetarderDSCHillMode43(String RetarderDSCHillMode43) 
	{
		this.RetarderDSCHillMode43 = RetarderDSCHillMode43;
	}
	
	public String getRetarderDSCHillMode44() 
	{
		return this.RetarderDSCHillMode44;
	}
	public void setRetarderDSCHillMode44(String RetarderDSCHillMode43) 
	{
		this.RetarderDSCHillMode43 = RetarderDSCHillMode43;
	}
	
}
