package aoc.Harlequin.OBJs;

// Generated 07 May 2018 11:58:04 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * PracticalDriversAssessment generated by hbm2java
 */
public class PracticalDriversAssessment implements java.io.Serializable {

	private int idPracticalDriversAssessment;
	private Integer idMacApplicants;
	private String name;
	private String surname;
	private String idNumber;
	private String clientName;
	private String pdpExpiryDate;
	private String vehicleUsed;
	private String assessorName;
	private String assessorSurname;
	private Integer assessorUserId;
	private String date;
	private String kmEnd;
	private String kmStart;
	private String timeEnd;
	private String timeStart;
	private String weather;
	private String route;
	private BigDecimal totalScore;
	private BigDecimal startingAndStopping;
	private BigDecimal generalDriving;
	private BigDecimal passingOrOvertaking;
	private BigDecimal generalRoadBehavior;
	private BigDecimal observationAndAnticipation;
	private BigDecimal approachingJunctionsTurningExiting;
	private BigDecimal reversing;
	private BigDecimal clutch;
	private BigDecimal retarderDscHillMode;
	private String comments;
	private Integer pdaNo;

	public PracticalDriversAssessment() {
	}

	public PracticalDriversAssessment(int idPracticalDriversAssessment) {
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
	}

	public PracticalDriversAssessment(int idPracticalDriversAssessment,
			Integer idMacApplicants, String name, String surname,
			String idNumber, String clientName, String pdpExpiryDate,
			String vehicleUsed, String assessorName, String assessorSurname,
			Integer assessorUserId, String date, String kmEnd, String kmStart,
			String timeEnd, String timeStart, String weather, String route,
			BigDecimal totalScore, BigDecimal startingAndStopping,
			BigDecimal generalDriving, BigDecimal passingOrOvertaking,
			BigDecimal generalRoadBehavior,
			BigDecimal observationAndAnticipation,
			BigDecimal approachingJunctionsTurningExiting,
			BigDecimal reversing, BigDecimal clutch,
			BigDecimal retarderDscHillMode, String comments, Integer pdaNo) {
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
		this.idMacApplicants = idMacApplicants;
		this.name = name;
		this.surname = surname;
		this.idNumber = idNumber;
		this.clientName = clientName;
		this.pdpExpiryDate = pdpExpiryDate;
		this.vehicleUsed = vehicleUsed;
		this.assessorName = assessorName;
		this.assessorSurname = assessorSurname;
		this.assessorUserId = assessorUserId;
		this.date = date;
		this.kmEnd = kmEnd;
		this.kmStart = kmStart;
		this.timeEnd = timeEnd;
		this.timeStart = timeStart;
		this.weather = weather;
		this.route = route;
		this.totalScore = totalScore;
		this.startingAndStopping = startingAndStopping;
		this.generalDriving = generalDriving;
		this.passingOrOvertaking = passingOrOvertaking;
		this.generalRoadBehavior = generalRoadBehavior;
		this.observationAndAnticipation = observationAndAnticipation;
		this.approachingJunctionsTurningExiting = approachingJunctionsTurningExiting;
		this.reversing = reversing;
		this.clutch = clutch;
		this.retarderDscHillMode = retarderDscHillMode;
		this.comments = comments;
		this.pdaNo = pdaNo;
	}

	public int getIdPracticalDriversAssessment() {
		return this.idPracticalDriversAssessment;
	}

	public void setIdPracticalDriversAssessment(int idPracticalDriversAssessment) {
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
	}

	public Integer getIdMacApplicants() {
		return this.idMacApplicants;
	}

	public void setIdMacApplicants(Integer idMacApplicants) {
		this.idMacApplicants = idMacApplicants;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getPdpExpiryDate() {
		return this.pdpExpiryDate;
	}

	public void setPdpExpiryDate(String pdpExpiryDate) {
		this.pdpExpiryDate = pdpExpiryDate;
	}

	public String getVehicleUsed() {
		return this.vehicleUsed;
	}

	public void setVehicleUsed(String vehicleUsed) {
		this.vehicleUsed = vehicleUsed;
	}

	public String getAssessorName() {
		return this.assessorName;
	}

	public void setAssessorName(String assessorName) {
		this.assessorName = assessorName;
	}

	public String getAssessorSurname() {
		return this.assessorSurname;
	}

	public void setAssessorSurname(String assessorSurname) {
		this.assessorSurname = assessorSurname;
	}

	public Integer getAssessorUserId() {
		return this.assessorUserId;
	}

	public void setAssessorUserId(Integer assessorUserId) {
		this.assessorUserId = assessorUserId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getKmEnd() {
		return this.kmEnd;
	}

	public void setKmEnd(String kmEnd) {
		this.kmEnd = kmEnd;
	}

	public String getKmStart() {
		return this.kmStart;
	}

	public void setKmStart(String kmStart) {
		this.kmStart = kmStart;
	}

	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	public String getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	public String getWeather() {
		return this.weather;
	}

	public void setWeather(String weather) {
		this.weather = weather;
	}

	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	public BigDecimal getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(BigDecimal totalScore) {
		this.totalScore = totalScore;
	}

	public BigDecimal getStartingAndStopping() {
		return this.startingAndStopping;
	}

	public void setStartingAndStopping(BigDecimal startingAndStopping) {
		this.startingAndStopping = startingAndStopping;
	}

	public BigDecimal getGeneralDriving() {
		return this.generalDriving;
	}

	public void setGeneralDriving(BigDecimal generalDriving) {
		this.generalDriving = generalDriving;
	}

	public BigDecimal getPassingOrOvertaking() {
		return this.passingOrOvertaking;
	}

	public void setPassingOrOvertaking(BigDecimal passingOrOvertaking) {
		this.passingOrOvertaking = passingOrOvertaking;
	}

	public BigDecimal getGeneralRoadBehavior() {
		return this.generalRoadBehavior;
	}

	public void setGeneralRoadBehavior(BigDecimal generalRoadBehavior) {
		this.generalRoadBehavior = generalRoadBehavior;
	}

	public BigDecimal getObservationAndAnticipation() {
		return this.observationAndAnticipation;
	}

	public void setObservationAndAnticipation(
			BigDecimal observationAndAnticipation) {
		this.observationAndAnticipation = observationAndAnticipation;
	}

	public BigDecimal getApproachingJunctionsTurningExiting() {
		return this.approachingJunctionsTurningExiting;
	}

	public void setApproachingJunctionsTurningExiting(
			BigDecimal approachingJunctionsTurningExiting) {
		this.approachingJunctionsTurningExiting = approachingJunctionsTurningExiting;
	}

	public BigDecimal getReversing() {
		return this.reversing;
	}

	public void setReversing(BigDecimal reversing) {
		this.reversing = reversing;
	}

	public BigDecimal getClutch() {
		return this.clutch;
	}

	public void setClutch(BigDecimal clutch) {
		this.clutch = clutch;
	}

	public BigDecimal getRetarderDscHillMode() {
		return this.retarderDscHillMode;
	}

	public void setRetarderDscHillMode(BigDecimal retarderDscHillMode) {
		this.retarderDscHillMode = retarderDscHillMode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Integer getPdaNo() {
		return this.pdaNo;
	}

	public void setPdaNo(Integer pdaNo) {
		this.pdaNo = pdaNo;
	}

}
