package aoc.Harlequin.OBJs;

// Generated 07 May 2018 11:58:04 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * PracticalDriversAssessment generated by hbm2java
 */
public class PracticalDriversAssessment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPracticalDriversAssessment;
	private Integer idMacApplicants;
	private String name;
	private String surname;
	private String idNumber;
	private String clientName;
	private String pdpExpiryDate;
	private String vehicleUsed;
	private String assessorName;
	private String assessorSurname;
	private Integer assessorUserId;
	private String date;
	private String kmEnd;
	private String kmStart;
	private String timeEnd;
	private String timeStart;
	private String weather;
	private String route;
	private BigDecimal totalScore;
	private BigDecimal startingAndStopping;
	private BigDecimal generalDriving;
	private BigDecimal passingOrOvertaking;
	private BigDecimal generalRoadBehavior;
	private BigDecimal observationAndAnticipation;
	private BigDecimal approachingJunctionsTurningExiting;
	private BigDecimal reversing;
	private BigDecimal clutch;
	private BigDecimal retarderDscHillMode;
	private String comments;
	private String pdaNo;
	private String licenseCode;
	private String practicalDriversTestComplete;
	private String practicalDriversTestComments;
	private String jobName;
	private String lastUsedDate;
	
	private int StartingAndStopping1;
	private int StartingAndStopping2;
	private int StartingAndStopping3;
	private int StartingAndStopping4;
	private int StartingAndStopping5;
	private int StartingAndStopping6;
	private int StartingAndStopping7;
	
	private int GeneralDriving8;
	private int GeneralDriving9;
	private int GeneralDriving10;
	private int GeneralDriving11;
	private int GeneralDriving12;
	private int GeneralDriving13;
	private int GeneralDriving14;
	private int GeneralDriving15;
	private int GeneralDriving16;
	private int GeneralDriving17;
	
	private int PassingOrOvertaking18;
	private int PassingOrOvertaking19;
	private int PassingOrOvertaking20;
	private int PassingOrOvertaking21;
	
	private int GeneralRoadBehavior22;
	private int GeneralRoadBehavior23;
	
	private int ObservationAndAnticipation24;
	private int ObservationAndAnticipation25;
	private int ObservationAndAnticipation26;
	private int ObservationAndAnticipation27;
	private int ObservationAndAnticipation28;
	
	private int ApproachingJunctionsTurningExiting29;
	private int ApproachingJunctionsTurningExiting30;
	private int ApproachingJunctionsTurningExiting31;
	private int ApproachingJunctionsTurningExiting32;
	private int ApproachingJunctionsTurningExiting33;
	private int ApproachingJunctionsTurningExiting34;
	private int ApproachingJunctionsTurningExiting35;
	private int ApproachingJunctionsTurningExiting36;
	
	private int Reversing37;
	private int Reversing38;
	private int Reversing39;
	
	private int Clutch40;
	private int Clutch41;
	
	private int RetarderDSCHillMode42;
	private int RetarderDSCHillMode43;
	private int RetarderDSCHillMode44;
	
	
	private String RoadTestPassed;
	private String ParkingTestPassed;

	private String RoadTestComments;
	private String ParkingTestComments;
	
	private String ReverseTestPassed;
	private String ReverseTestComments;

	public PracticalDriversAssessment() 
	{
		
	}

	public PracticalDriversAssessment(int idPracticalDriversAssessment) 
	{
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
	}

	public PracticalDriversAssessment(int idPracticalDriversAssessment,
			Integer idMacApplicants, String name, String surname,
			String idNumber, String clientName, String pdpExpiryDate,
			String vehicleUsed, String assessorName, String assessorSurname,
			Integer assessorUserId, String date, String kmEnd, String kmStart,
			String timeEnd, String timeStart, String weather, String route,
			BigDecimal totalScore, BigDecimal startingAndStopping,
			BigDecimal generalDriving, BigDecimal passingOrOvertaking,
			BigDecimal generalRoadBehavior,
			BigDecimal observationAndAnticipation,
			BigDecimal approachingJunctionsTurningExiting,
			BigDecimal reversing, BigDecimal clutch,
			BigDecimal retarderDscHillMode, String comments, String pdaNo,
			String licenseCode,String practicalDriversTestComplete,String practicalDriversTestComments,
			String jobName, String lastUsedDate,
			int StartingAndStopping1, int StartingAndStopping2, int StartingAndStopping3, int StartingAndStopping4, int StartingAndStopping5, int StartingAndStopping6, int StartingAndStopping7,
			int GeneralDriving8, int GeneralDriving9, int GeneralDriving10, int GeneralDriving11, int GeneralDriving12, int GeneralDriving13, int GeneralDriving14, int GeneralDriving15, int GeneralDriving16, int GeneralDriving17,
			int PassingOrOvertaking18, int PassingOrOvertaking19, int PassingOrOvertaking20, int PassingOrOvertaking21,
			int GeneralRoadBehavior22, int GeneralRoadBehavior23,
			int ObservationAndAnticipation24, int ObservationAndAnticipation25, int ObservationAndAnticipation26, int ObservationAndAnticipation27,  int ObservationAndAnticipation28,
			int ApproachingJunctionsTurningExiting29,int ApproachingJunctionsTurningExiting30, int ApproachingJunctionsTurningExiting31,int ApproachingJunctionsTurningExiting32, int ApproachingJunctionsTurningExiting33, int ApproachingJunctionsTurningExiting34, int ApproachingJunctionsTurningExiting35,int ApproachingJunctionsTurningExiting36,
			int Reversing37, int Reversing38, int Reversing39,
			int Clutch40, int Clutch41,
			int RetarderDSCHillMode42, int RetarderDSCHillMode43, int RetarderDSCHillMode44,
			String ParkingTestPassed, String RoadTestPassed, String ParkingTestComments, String RoadTestComments, 
			String ReverseTestPassed, String ReverseTestComments) {
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
		this.idMacApplicants = idMacApplicants;
		this.name = name;
		this.surname = surname;
		this.idNumber = idNumber;
		this.clientName = clientName;
		this.pdpExpiryDate = pdpExpiryDate;
		this.vehicleUsed = vehicleUsed;
		this.assessorName = assessorName;
		this.assessorSurname = assessorSurname;
		this.assessorUserId = assessorUserId;
		this.date = date;
		this.kmEnd = kmEnd;
		this.kmStart = kmStart;
		this.timeEnd = timeEnd;
		this.timeStart = timeStart;
		this.weather = weather;
		this.route = route;
		this.totalScore = totalScore;
		this.startingAndStopping = startingAndStopping;
		this.generalDriving = generalDriving;
		this.passingOrOvertaking = passingOrOvertaking;
		this.generalRoadBehavior = generalRoadBehavior;
		this.observationAndAnticipation = observationAndAnticipation;
		this.approachingJunctionsTurningExiting = approachingJunctionsTurningExiting;
		this.reversing = reversing;
		this.clutch = clutch;
		this.retarderDscHillMode = retarderDscHillMode;
		this.comments = comments;
		this.pdaNo = pdaNo;
		this.licenseCode = licenseCode;
		this.practicalDriversTestComplete = practicalDriversTestComplete;
		this.practicalDriversTestComments = practicalDriversTestComments;
		this.jobName = jobName;
		this.lastUsedDate = lastUsedDate;
		
		this.StartingAndStopping1 = StartingAndStopping1; 
		this.StartingAndStopping2 = StartingAndStopping2;
		this.StartingAndStopping3 = StartingAndStopping3; 
		this.StartingAndStopping4 = StartingAndStopping4;
		this.StartingAndStopping5 = StartingAndStopping5; 
		this.StartingAndStopping6 = StartingAndStopping6;
		this.StartingAndStopping7 = StartingAndStopping7;
		
		this.GeneralDriving8 = GeneralDriving8;
		this.GeneralDriving9 = GeneralDriving9;
		this.GeneralDriving10 = GeneralDriving10;
		this.GeneralDriving11 = GeneralDriving11;
		this.GeneralDriving12 = GeneralDriving12;
		this.GeneralDriving13 = GeneralDriving13;
		this.GeneralDriving14 = GeneralDriving14;
		this.GeneralDriving15 = GeneralDriving15;
		this.GeneralDriving16 = GeneralDriving16;
		this.GeneralDriving17 = GeneralDriving17;
		
		this.PassingOrOvertaking18 = PassingOrOvertaking18;
		this.PassingOrOvertaking19 = PassingOrOvertaking19;
		this.PassingOrOvertaking20 = PassingOrOvertaking20;
		this.PassingOrOvertaking21 = PassingOrOvertaking21;
		
		
		this.GeneralRoadBehavior22 = GeneralRoadBehavior22;
		this.GeneralRoadBehavior23 = GeneralRoadBehavior23;
		
		this.ObservationAndAnticipation24 = ObservationAndAnticipation24;
		this.ObservationAndAnticipation25 = ObservationAndAnticipation25;
		this.ObservationAndAnticipation26 = ObservationAndAnticipation26;
		this.ObservationAndAnticipation27 = ObservationAndAnticipation27;
		this.ObservationAndAnticipation28 = ObservationAndAnticipation28;
		
		
		this.ApproachingJunctionsTurningExiting29 = ApproachingJunctionsTurningExiting29;
		this.ApproachingJunctionsTurningExiting30 = ApproachingJunctionsTurningExiting30;
		this.ApproachingJunctionsTurningExiting31 = ApproachingJunctionsTurningExiting31;
		this.ApproachingJunctionsTurningExiting32 = ApproachingJunctionsTurningExiting32;
		this.ApproachingJunctionsTurningExiting33 = ApproachingJunctionsTurningExiting33;
		this.ApproachingJunctionsTurningExiting34 = ApproachingJunctionsTurningExiting34;
		this.ApproachingJunctionsTurningExiting35 = ApproachingJunctionsTurningExiting35;
		this.ApproachingJunctionsTurningExiting36 = ApproachingJunctionsTurningExiting36;
		
		this.Reversing37 = Reversing37;
		this.Reversing38 = Reversing38;
		this.Reversing39 = Reversing39;
		
		this.Clutch40 = Clutch40;
		this.Clutch41 = Clutch41;
		
		this.RetarderDSCHillMode42 = RetarderDSCHillMode42;
		this.RetarderDSCHillMode43 = RetarderDSCHillMode43;
		this.RetarderDSCHillMode44 = RetarderDSCHillMode44; 
		
		this.RoadTestPassed = RoadTestPassed;
		this.ParkingTestPassed = ParkingTestPassed;
		
		this.RoadTestComments = RoadTestComments;
		this.ParkingTestComments = ParkingTestComments;
		
		this.ReverseTestPassed = ReverseTestPassed;
		this.ReverseTestComments = ReverseTestComments;
		
	}

	
	
	
	public String getReverseTestPassed()
	{
		return this.ReverseTestPassed;
	}
	public void setReverseTestPassed(String ReverseTestPassed) 
	{
		this.ReverseTestPassed = ReverseTestPassed;
	}
	
	
	public String getReverseTestComments()
	{
		return this.ReverseTestComments;
	}
	public void setReverseTestComments(String ReverseTestComments) 
	{
		this.ReverseTestComments = ReverseTestComments;
	}
	
	public String getParkingTestComments()
	{
		return this.ParkingTestComments;
	}
	public void setParkingTestComments(String ParkingTestComments) 
	{
		this.ParkingTestComments = ParkingTestComments;
	}

	
	public String getRoadTestComments()
	{
		return this.RoadTestComments;
	}
	public void setRoadTestComments(String RoadTestComments) 
	{
		this.RoadTestComments = RoadTestComments;
	}
	
	
	public String getRoadTestPassed()
	{
		return this.RoadTestPassed;
	}

	public void setRoadTestPassed(String RoadTestPassed) 
	{
		this.RoadTestPassed = RoadTestPassed;
	}
	
	public String getParkingTestPassed()
	{
		return this.ParkingTestPassed;
	}

	public void setParkingTestPassed(String ParkingTestPassed) 
	{
		this.ParkingTestPassed = ParkingTestPassed;
	}
	
	
	public String getLastUsedDate()
	{
		return this.lastUsedDate;
	}

	public void setLastUsedDate(String lastUsedDate) 
	{
		this.lastUsedDate = lastUsedDate;
	}
	
	public String getjobName()
	{
		return this.jobName;
	}

	public void setjobName(String jobName) 
	{
		this.jobName = jobName;
	}
	
	
	
	public int getIdPracticalDriversAssessment()
	{
		return this.idPracticalDriversAssessment;
	}

	public void setIdPracticalDriversAssessment(int idPracticalDriversAssessment) 
	{
		this.idPracticalDriversAssessment = idPracticalDriversAssessment;
	}

	public Integer getIdMacApplicants() 
	{
		return this.idMacApplicants;
	}

	public void setIdMacApplicants(Integer idMacApplicants) 
	{
		this.idMacApplicants = idMacApplicants;
	}

	public String getName() 
	{
		return this.name;
	}

	public void setName(String name) 
	{
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getPdpExpiryDate() {
		return this.pdpExpiryDate;
	}

	public void setPdpExpiryDate(String pdpExpiryDate) {
		this.pdpExpiryDate = pdpExpiryDate;
	}

	public String getVehicleUsed() {
		return this.vehicleUsed;
	}

	public void setVehicleUsed(String vehicleUsed) {
		this.vehicleUsed = vehicleUsed;
	}

	public String getAssessorName() {
		return this.assessorName;
	}

	public void setAssessorName(String assessorName) {
		this.assessorName = assessorName;
	}

	public String getAssessorSurname() {
		return this.assessorSurname;
	}

	public void setAssessorSurname(String assessorSurname) {
		this.assessorSurname = assessorSurname;
	}

	public Integer getAssessorUserId() {
		return this.assessorUserId;
	}

	public void setAssessorUserId(Integer assessorUserId) {
		this.assessorUserId = assessorUserId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getKmEnd() {
		return this.kmEnd;
	}

	public void setKmEnd(String kmEnd) {
		this.kmEnd = kmEnd;
	}

	public String getKmStart() {
		return this.kmStart;
	}

	public void setKmStart(String kmStart) {
		this.kmStart = kmStart;
	}

	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	public String getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	public String getWeather() {
		return this.weather;
	}

	public void setWeather(String weather) {
		this.weather = weather;
	}

	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	public BigDecimal getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(BigDecimal totalScore) {
		this.totalScore = totalScore;
	}

	public BigDecimal getStartingAndStopping() {
		return this.startingAndStopping;
	}

	public void setStartingAndStopping(BigDecimal startingAndStopping) {
		this.startingAndStopping = startingAndStopping;
	}

	public BigDecimal getGeneralDriving() {
		return this.generalDriving;
	}

	public void setGeneralDriving(BigDecimal generalDriving) {
		this.generalDriving = generalDriving;
	}

	public BigDecimal getPassingOrOvertaking() {
		return this.passingOrOvertaking;
	}

	public void setPassingOrOvertaking(BigDecimal passingOrOvertaking) {
		this.passingOrOvertaking = passingOrOvertaking;
	}

	public BigDecimal getGeneralRoadBehavior() {
		return this.generalRoadBehavior;
	}

	public void setGeneralRoadBehavior(BigDecimal generalRoadBehavior) {
		this.generalRoadBehavior = generalRoadBehavior;
	}

	public BigDecimal getObservationAndAnticipation() {
		return this.observationAndAnticipation;
	}

	public void setObservationAndAnticipation(
			BigDecimal observationAndAnticipation) {
		this.observationAndAnticipation = observationAndAnticipation;
	}

	public BigDecimal getApproachingJunctionsTurningExiting() {
		return this.approachingJunctionsTurningExiting;
	}

	public void setApproachingJunctionsTurningExiting(
			BigDecimal approachingJunctionsTurningExiting) {
		this.approachingJunctionsTurningExiting = approachingJunctionsTurningExiting;
	}

	public BigDecimal getReversing() {
		return this.reversing;
	}

	public void setReversing(BigDecimal reversing) {
		this.reversing = reversing;
	}

	public BigDecimal getClutch() {
		return this.clutch;
	}

	public void setClutch(BigDecimal clutch) {
		this.clutch = clutch;
	}

	public BigDecimal getRetarderDscHillMode() {
		return this.retarderDscHillMode;
	}

	public void setRetarderDscHillMode(BigDecimal retarderDscHillMode) {
		this.retarderDscHillMode = retarderDscHillMode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getPdaNo() {
		return this.pdaNo;
	}

	public String getLicenseCode() {
		return this.licenseCode;
	}
	
	public void setPdaNo(String pdaNo) {
		this.pdaNo = pdaNo;
	}

	public void setLicenseCode(String license_Code) 
	{
		// TODO Auto-generated method stub
		this.licenseCode = license_Code;
	}
	
	

	public String getPracticalDriversTestComplete() 
	{
		return this.practicalDriversTestComplete;
	}

	public void setPracticalDriversTestComplete(String practicalDriversTestComplete) 
	{
		this.practicalDriversTestComplete = practicalDriversTestComplete;
	}

	
	public String getPracticalDriversTestComments() 
	{
		return this.practicalDriversTestComments;
	}

	public void setPracticalDriversTestComments(String practicalDriversTestComments) 
	{
		this.practicalDriversTestComments = practicalDriversTestComments;
	}
	
	
	
	public int getStartingAndStopping1() 
	{
		return this.StartingAndStopping1;
	}
	public void setStartingAndStopping1(int StartingAndStopping1) 
	{
		this.StartingAndStopping1 = StartingAndStopping1;
	}
	
	public int getStartingAndStopping2() 
	{
		return this.StartingAndStopping2;
	}
public void setStartingAndStopping2(int StartingAndStopping2) 
	{
		this.StartingAndStopping2 = StartingAndStopping2;
	}
	
	public int getStartingAndStopping3() 
	{
		return this.StartingAndStopping3;
	}
	public void setStartingAndStopping3(int StartingAndStopping3) 
	{
		this.StartingAndStopping3 = StartingAndStopping3;
	}
	
	public int getStartingAndStopping4() 
	{
		return this.StartingAndStopping4;
	}
	public void setStartingAndStopping4(int StartingAndStopping4) 
	{
		this.StartingAndStopping4 = StartingAndStopping4;
	}
	
	public int getStartingAndStopping5() 
	{
		return this.StartingAndStopping5;
	}
	public void setStartingAndStopping5(int StartingAndStopping5) 
	{
		this.StartingAndStopping5 = StartingAndStopping5;
	}
	
	public int getStartingAndStopping6() 
	{
		return this.StartingAndStopping6;
	}
	public void setStartingAndStopping6(int StartingAndStopping6) 
	{
		this.StartingAndStopping6 = StartingAndStopping6;
	}
	
	public int getStartingAndStopping7() 
	{
		return this.StartingAndStopping7;
	}
	public void setStartingAndStopping7(int StartingAndStopping7) 
	{
		this.StartingAndStopping7 = StartingAndStopping7;
	}
	
	
	public int getGeneralDriving8() 
	{
		return this.GeneralDriving8;
	}
	public void setGeneralDriving8(int GeneralDriving8) 
	{
		this.GeneralDriving8 = GeneralDriving8;
	}
	
	public int getGeneralDriving9() 
	{
		return this.GeneralDriving9;
	}
	public void setGeneralDriving9(int GeneralDriving9) 
	{
		this.GeneralDriving9 = GeneralDriving9;
	}

	public int getGeneralDriving10() 
	{
		return this.GeneralDriving10;
	}
	public void setGeneralDriving10(int GeneralDriving10) 
	{
		this.GeneralDriving10 = GeneralDriving10;
	}
	
	public int getGeneralDriving11() 
	{
		return this.GeneralDriving11;
	}
	public void setGeneralDriving11(int GeneralDriving11) 
	{
		this.GeneralDriving11 = GeneralDriving11;
	}
	
	public int getGeneralDriving12() 
	{
		return this.GeneralDriving12;
	}
	public void setGeneralDriving12(int GeneralDriving12) 
	{
		this.GeneralDriving12 = GeneralDriving12;
	}
	
	public int getGeneralDriving13() 
	{
		return this.GeneralDriving13;
	}
	public void setGeneralDriving13(int GeneralDriving13) 
	{
		this.GeneralDriving13 = GeneralDriving13;
	}
	
	public int getGeneralDriving14() 
	{
		return this.GeneralDriving14;
	}
	public void setGeneralDriving14(int GeneralDriving14) 
	{
		this.GeneralDriving14 = GeneralDriving14;
	}
	
	public int getGeneralDriving15() 
	{
		return this.GeneralDriving15;
	}
	public void setGeneralDriving15(int GeneralDriving15) 
	{
		this.GeneralDriving15 = GeneralDriving15;
	}
	
	public int getGeneralDriving16() 
	{
		return this.GeneralDriving16;
	}
	public void setGeneralDriving16(int GeneralDriving16) 
	{
		this.GeneralDriving16 = GeneralDriving16;
	}
	
	
	public int getGeneralDriving17() 
	{
		return this.GeneralDriving17;
	}
	public void setGeneralDriving17(int GeneralDriving17) 
	{
		this.GeneralDriving17 = GeneralDriving17;
	}
	
	
	public int getPassingOrOvertaking18() 
	{
		return this.PassingOrOvertaking18;
	}
	public void setPassingOrOvertaking18(int PassingOrOvertaking18) 
	{
		this.PassingOrOvertaking18 = PassingOrOvertaking18;
	}
	public int getPassingOrOvertaking19() 
	{
		return this.PassingOrOvertaking19;
	}
	public void setPassingOrOvertaking19(int PassingOrOvertaking19) 
	{
		this.PassingOrOvertaking19 = PassingOrOvertaking19;
	}
	public int getPassingOrOvertaking20() 
	{
		return this.PassingOrOvertaking20;
	}
	public void setPassingOrOvertaking20(int PassingOrOvertaking20) 
	{
		this.PassingOrOvertaking20 = PassingOrOvertaking20;
	}
	
	public int getPassingOrOvertaking21() 
	{
		return this.PassingOrOvertaking21;
	}
	public void setPassingOrOvertaking21(int PassingOrOvertaking21) 
	{
		this.PassingOrOvertaking21 = PassingOrOvertaking21;
	}
	
	public int getGeneralRoadBehavior22() 
	{
		return this.GeneralRoadBehavior22;
	}
	public void setGeneralRoadBehavior22(int GeneralRoadBehavior22) 
	{
		this.GeneralRoadBehavior22 = GeneralRoadBehavior22;
	}
	
	public int getGeneralRoadBehavior23() 
	{
		return this.GeneralRoadBehavior23;
	}
	public void setGeneralRoadBehavior23(int GeneralRoadBehavior23) 
	{
		this.GeneralRoadBehavior23 = GeneralRoadBehavior23;
	}
	
	public int getObservationAndAnticipation24() 
	{
		return this.ObservationAndAnticipation24;
	}
	public void setObservationAndAnticipation24(int ObservationAndAnticipation24) 
	{
		this.ObservationAndAnticipation24 = ObservationAndAnticipation24;
	}
	
	public int getObservationAndAnticipation25() 
	{
		return this.ObservationAndAnticipation25;
	}
	public void setObservationAndAnticipation25(int ObservationAndAnticipation25) 
	{
		this.ObservationAndAnticipation25 = ObservationAndAnticipation25;
	}
	
	public int getObservationAndAnticipation26() 
	{
		return this.ObservationAndAnticipation26;
	}
	public void setObservationAndAnticipation26(int ObservationAndAnticipation26) 
	{
		this.ObservationAndAnticipation26 = ObservationAndAnticipation26;
	}
	
	public int getObservationAndAnticipation27() 
	{
		return this.ObservationAndAnticipation27;
	}
	public void setObservationAndAnticipation27(int ObservationAndAnticipation27) 
	{
		this.ObservationAndAnticipation27 = ObservationAndAnticipation27;
	}
	
	public int getObservationAndAnticipation28() 
	{
		return this.ObservationAndAnticipation28;
	}
	public void setObservationAndAnticipation28(int ObservationAndAnticipation28) 
	{
		this.ObservationAndAnticipation28 = ObservationAndAnticipation28;
	}
	
	public int getApproachingJunctionsTurningExiting29() 
	{
		return this.ApproachingJunctionsTurningExiting29;
	}
	public void setApproachingJunctionsTurningExiting29(int ApproachingJunctionsTurningExiting29) 
	{
		this.ApproachingJunctionsTurningExiting29 = ApproachingJunctionsTurningExiting29;
	}
	
	
	public int getApproachingJunctionsTurningExiting30() 
	{
		return this.ApproachingJunctionsTurningExiting30;
	}
	public void setApproachingJunctionsTurningExiting30(int ApproachingJunctionsTurningExiting30) 
	{
		this.ApproachingJunctionsTurningExiting30 = ApproachingJunctionsTurningExiting30;
	}
	
	public int getApproachingJunctionsTurningExiting31() 
	{
		return this.ApproachingJunctionsTurningExiting31;
	}
	public void setApproachingJunctionsTurningExiting31(int ApproachingJunctionsTurningExiting31) 
	{
		this.ApproachingJunctionsTurningExiting31 = ApproachingJunctionsTurningExiting31;
	}
	
	public int getApproachingJunctionsTurningExiting32() 
	{
		return this.ApproachingJunctionsTurningExiting32;
	}
	public void setApproachingJunctionsTurningExiting32(int ApproachingJunctionsTurningExiting32) 
	{
		this.ApproachingJunctionsTurningExiting32 = ApproachingJunctionsTurningExiting32;
	}

	
	public int getApproachingJunctionsTurningExiting33() 
	{
		return this.ApproachingJunctionsTurningExiting33;
	}
	public void setApproachingJunctionsTurningExiting33(int ApproachingJunctionsTurningExiting33) 
	{
		this.ApproachingJunctionsTurningExiting33 = ApproachingJunctionsTurningExiting33;
	}
	
	public int getApproachingJunctionsTurningExiting34() 
	{
		return this.ApproachingJunctionsTurningExiting34;
	}
	public void setApproachingJunctionsTurningExiting34(int ApproachingJunctionsTurningExiting34) 
	{
		this.ApproachingJunctionsTurningExiting34 = ApproachingJunctionsTurningExiting34;
	}
	
	public int getApproachingJunctionsTurningExiting35() 
	{
		return this.ApproachingJunctionsTurningExiting35;
	}
	public void setApproachingJunctionsTurningExiting35(int ApproachingJunctionsTurningExiting35) 
	{
		this.ApproachingJunctionsTurningExiting35 = ApproachingJunctionsTurningExiting35;
	}
	
	public int getApproachingJunctionsTurningExiting36() 
	{
		return this.ApproachingJunctionsTurningExiting36;
	}
	public void setApproachingJunctionsTurningExiting36(int ApproachingJunctionsTurningExiting36) 
	{
		this.ApproachingJunctionsTurningExiting36 = ApproachingJunctionsTurningExiting36;
	}
	
	
	public int getReversing37() 
	{
		return this.Reversing37;
	}
	public void setReversing37(int Reversing37) 
	{
		this.Reversing37 = Reversing37;
	}
	public int getReversing38() 
	{
		return this.Reversing38;
	}
	public void setReversing38(int Reversing38) 
	{
		this.Reversing38 = Reversing38;
	}
	
	public int getReversing39() 
	{
		return this.Reversing39;
	}
	public void setReversing39(int Reversing39) 
	{
		this.Reversing39 = Reversing39;
	}
	
	public int getClutch40() 
	{
		return this.Clutch40;
	}
	public void setClutch40(int Clutch40) 
	{
		this.Clutch40 = Clutch40;
	}
	public int getClutch41() 
	{
		return this.Clutch41;
	}
	public void setClutch41(int Clutch41) 
	{
		this.Clutch41 = Clutch41;
	}
	
	
	public int getRetarderDSCHillMode42() 
	{
		return this.RetarderDSCHillMode42;
	}
	public void setRetarderDSCHillMode42(int RetarderDSCHillMode42) 
	{
		this.RetarderDSCHillMode42 = RetarderDSCHillMode42;
	}
	
	public int getRetarderDSCHillMode43() 
	{
		return this.RetarderDSCHillMode43;
	}
	public void setRetarderDSCHillMode43(int RetarderDSCHillMode43) 
	{
		this.RetarderDSCHillMode43 = RetarderDSCHillMode43;
	}
	
	public int getRetarderDSCHillMode44() 
	{
		return this.RetarderDSCHillMode44;
	}
	public void setRetarderDSCHillMode44(int RetarderDSCHillMode44) 
	{
		this.RetarderDSCHillMode44 = RetarderDSCHillMode44;
	}
	
}
