package aoc.Harlequin.OBJs;

// Generated 06 Mar 2018 11:04:37 AM by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idUsers;
	private String userName;
	private String name;
	private String surname;
	private String idNumber;

	public Users() {
	}

	public Users(String userName, String name, String surname, String idNumber) {
		this.userName = userName;
		this.name = name;
		this.surname = surname;
		this.idNumber = idNumber;
	}

	public Integer getIdUsers() {
		return this.idUsers;
	}

	public void setIdUsers(Integer idUsers) {
		this.idUsers = idUsers;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

}
